### ISSUE TITLE
bug: split/spread drops remainders

### ISSUE THREAD

**Issue by Akuukis** [Akuukis/beancount-interpolate#18]
### Repro

```
plugin "beancount_interpolate.split" "{}"

2020-01-01 open Assets:Cash
2020-01-01 open Expenses:Random

2020-06-01 * "shop" "cookies" #split-month
    Expenses:Random  0.13 EUR
    Assets:Cash
```

### Actual behavior

Generates two transactions of 5 cents each.

### Expected behavior

Either
1. generate 3 transactions with 5, 5 and 3 cents.
2. generate 2 transactions with 5 and 8 cents.

### Notes

Same happens with `#spread-month` instead of `#split-month`.

**Comment by RonMcKay** [comment]
I worked on a fix for that and it seems like only a small change is able to solve it. I am however thinking about how we should handle the remainder.
I would definitely propose to **NOT** generate an additional transaction with an amount smaller then the configured `min_value` as this would cause confusion and might not be possible to fit in the requested period.

So we either add the total remainder to the last transaction (this is quite easy to implement) or try to split the remainder on all transactions, starting at `begin_date`. This would have the advantage of not creating a 'spike' in the amounts, which this plugin is all about. This would thus result in two transactions with 7 and 6 cents.
@Akuukis: What do you think about the two possibilities?

When we consider something like:

```
plugin "beancount_interpolate.split" "{}"

2020-01-01 open Assets:Cash
2020-01-01 open Expenses:Random

2020-06-01 * "shop" "cookies" #split-month
    Expenses:Random  0.04 EUR
    Assets:Cash
```

Then there has to be a transaction with an amount smaller than `min_value`. In this case I would just insert the transaction at `begin_date`.

**Comment by Akuukis** [comment]
1. I prefer simple solution, and up to 5 cent "spike" at the end is not a big deal.
2. I prefer to have one transaction at `begin_date` even with amount less than `min_value`, than to lose any cents anywhere.
