### ISSUE TITLE
cannot import `beancount-interpolate` because `-` in the module name

### ISSUE THREAD

**Issue by zhou13** [Akuukis/beancount-interpolate#2]
Hi Akuukis, I am not sure if I install the package correctly. But since `beancount-interpolate` contains `-`, I do not think it is possible to import it into python. My beancount complains `Error importing "beancount-interpolate.depr": No module named 'beancount-interpolate.depr'`.

**Comment by zhou13** [comment]
It seems that `depr` should be `depreciate`.

**Comment by Akuukis** [comment]
Interesting, I've never imported it into python directly before, only as plugin for beancount.

I'm planning to get back to python and fix all bugs in few months. If you figure it out beforehand please come back and tell me too ;)

**Comment by Akuukis** [comment]
Indeed, [Python docs](https://docs.python-guide.org/writing/structure/#modules) reads:
> If you’d like you could name your module my_spam.py, but even our friend the underscore should not be seen often in module names. However, using other characters (spaces or hyphens) in module names will prevent importing (- is the subtract operator), so try to keep module names short so there is no need to separate words. And, most of all, don’t namespace with underscores; use submodules instead.

I've renamed module and uploaded it as of [2.1.3](https://pypi.org/project/beancount_interpolate/). Therefore 2.1.2 is the last version using the old name.

**Comment by Akuukis** [comment]
The weird part is that underscore link redirects to dash link, but it works anyways:
```sh
$ pip3 install beancount_oneliner --upgrade
Collecting beancount_oneliner
  Downloading https://files.pythonhosted.org/packages/e9/af/e3519ecca1c230b97302f9462d9378b3543429390b5830fccc92da464ffd/beancount_oneliner-1.0.5-py3-none-any.whl
Installing collected packages: beancount-oneliner
Successfully installed beancount-oneliner-1.0.5
$ python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from beancount_oneliner import oneliner
>>>
```
